### ISSUE TITLE
Command be called using lua syntax

### ISSUE THREAD

**Issue by niderhoff** [kyoh86/telescope-windows.nvim#2]
Hi,

I am having trouble calling this extension using the lua syntax.
This *does not work*:
```
:lua require('telescope').extensions.windows.windows()
```
*neither does this*:
```
:lua require('telescope').extensions.windows()
```
Conesequently, we cannot make key bindings using the lua syntax.

However, using vim syntax works:
```
:Telescope windows
```

and so does the binding:
```
nnoremap <leader>fw <cmd>Telescope windows<cr>
```

I tried to this in the first place, because I want to customize the options of the picker and it seems like I cannot configure it like so:

```
lua << EOF
    require('telescope').setup {
        extensions = {
            windows = {
                preview = false
            }
        }
    }
    require'telescope'.load_extension'windows'
EOF
```

**Comment by kyoh86** [comment]
It's fixed by #3.
Please setup that like below.

```lua
    require('telescope').setup {
        extensions = {
            windows = {
                previewer = false
            }
        }
    }
    require'telescope'.load_extension'windows'
```

NOTE the property is not `preview`, but `previewer`
