### ISSUE TITLE
Wrong install Url?

### ISSUE THREAD

**Issue by TheJoeSchr** [kyoh86/telescope-windows.nvim#4]
Shouldn't that be `kyoh86/telescope-windows.nvim`?

At least with `Plug 'nvim-telescope/telescope-windows.nvim' I get this error:
```
x telescope-windows.nvim:
    Cloning into '/home/joe/.vim/plugged/telescope-windows.nvim'...
    remote: Repository not found.
    fatal: repository 'https://github.com/nvim-telescope/telescope-windows.nvim.git/' not found
```
`

**Comment by kyoh86** [comment]
thanks. I'll delete it.

**Comment by kyoh86** [comment]
done.

**Comment by TheJoeSchr** [comment]
I think deleting is a bit overkill, probably just changing to `Plug 'kyoh86/telescope-windows.nvim'` would have been fine :D
