### ISSUE TITLE
Current window as default selection

### ISSUE THREAD

**Issue by andrevmatos** [kyoh86/telescope-windows.nvim#5]
It'd be cool to have the current window be the selected one in the list, to make it easier to move to the previous/next windows.
Also, some shortcut to close the selected window would also be very welcome, maybe `n:D` and `i:<C-Del>` to not conflict with preview?
Thanks for this plugin.

**Comment by kyoh86** [comment]
I no longer use telescope.nvim and have moved to using ddu.vim.
The telescope.nvim interface is very difficult to create an extension for, and I have no plans to make any new enhancements to this extension either.
Sorry.
